import { Vehicle, Appointment, BuybackRequest, VehicleAlert, Availability } from "@/types";

export const SITE_CONFIG = {
  name: "RJ Auto",
  address: "10 Pl. de la République, 93140 Bondy",
  phone: "07 86 34 09 94",
  phoneFormatted: "07 86 34 09 94",
  phoneLink: "tel:+33786340994",
  whatsappLink: "https://wa.me/33786340994",
  hours: "10h - 20h, 7j/7",
  email: "contact@rjauto.fr",
  description: "Achat-revente de véhicules d'occasion à Bondy. Garantie incluse, véhicules révisés et contrôlés.",
  mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2622.5!2d2.4834!3d48.9025!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66d5e6b2f1b3d%3A0x0!2s10+Place+de+la+R%C3%A9publique%2C+93140+Bondy!5e0!3m2!1sfr!2sfr!4v1",
};

export const mockVehicles: Vehicle[] = [
  {
    id: "1",
    slug: "peugeot-308-style-2020",
    brand: "Peugeot",
    model: "308 Style",
    year: 2020,
    mileage: 45000,
    price: 16900,
    fuel: "Diesel",
    transmission: "Manuelle",
    color: "Gris Artense",
    doors: 5,
    seats: 5,
    power: "130 ch",
    engine: "1.5 BlueHDi",
    description: "Peugeot 308 en excellent état, entretien suivi en concession. Carnet d'entretien complet disponible. Véhicule non-fumeur, première main. Idéale pour les trajets quotidiens comme pour les longs voyages, cette 308 offre un confort de conduite remarquable et une consommation maîtrisée.",
    positivePoints: [
      "Carnet d'entretien complet",
      "Première main",
      "Révision à jour",
      "Pneus neufs",
      "Contrôle technique OK",
      "Climatisation automatique bi-zone",
    ],
    negativePoints: [
      "Micro-rayure aile arrière droite",
      "Léger frottement pare-chocs avant",
    ],
    images: [
      "/mock/vehicles/peugeot-308-1.jpg",
      "/mock/vehicles/peugeot-308-2.jpg",
      "/mock/vehicles/peugeot-308-3.jpg",
      "/mock/vehicles/peugeot-308-4.jpg",
    ],
    featured: true,
    published: true,
    createdAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "2",
    slug: "renault-clio-5-intens-2021",
    brand: "Renault",
    model: "Clio 5 Intens",
    year: 2021,
    mileage: 32000,
    price: 15500,
    fuel: "Essence",
    transmission: "Manuelle",
    color: "Blanc Glacier",
    doors: 5,
    seats: 5,
    power: "100 ch",
    engine: "1.0 TCe",
    description: "Renault Clio 5 finition Intens, très bien équipée. GPS, caméra de recul, aide au stationnement. Véhicule idéal en ville comme sur route. Faible consommation et entretien régulier effectué chez Renault.",
    positivePoints: [
      "Faible kilométrage",
      "GPS intégré",
      "Caméra de recul",
      "Entretien chez Renault",
      "Garantie constructeur restante",
    ],
    negativePoints: [
      "Petit impact sur pare-brise (hors champ de vision)",
    ],
    images: [
      "/mock/vehicles/renault-clio-1.jpg",
      "/mock/vehicles/renault-clio-2.jpg",
      "/mock/vehicles/renault-clio-3.jpg",
    ],
    featured: true,
    published: true,
    createdAt: "2026-08-05T10:00:00Z",
  },
  {
    id: "3",
    slug: "volkswagen-golf-8-life-2021",
    brand: "Volkswagen",
    model: "Golf 8 Life",
    year: 2021,
    mileage: 55000,
    price: 22900,
    fuel: "Diesel",
    transmission: "Automatique",
    color: "Noir Intense",
    doors: 5,
    seats: 5,
    power: "150 ch",
    engine: "2.0 TDI DSG7",
    description: "Volkswagen Golf 8 finition Life, boîte automatique DSG7. Véhicule très agréable à conduire, motorisation performante et économique. Sellerie tissu/alcantara en parfait état. Toutes options de confort et sécurité.",
    positivePoints: [
      "Boîte automatique DSG7",
      "Sellerie alcantara parfait état",
      "Régulateur adaptatif",
      "LED Matrix",
      "Révision complète effectuée",
      "4 pneus récents",
    ],
    negativePoints: [
      "Légères traces d'usure volant",
    ],
    images: [
      "/mock/vehicles/vw-golf-1.jpg",
      "/mock/vehicles/vw-golf-2.jpg",
      "/mock/vehicles/vw-golf-3.jpg",
      "/mock/vehicles/vw-golf-4.jpg",
    ],
    featured: true,
    published: true,
    createdAt: "2026-08-08T10:00:00Z",
  },
  {
    id: "4",
    slug: "bmw-serie-3-320d-2019",
    brand: "BMW",
    model: "Série 3 320d",
    year: 2019,
    mileage: 78000,
    price: 27500,
    fuel: "Diesel",
    transmission: "Automatique",
    color: "Gris Mineral",
    doors: 4,
    seats: 5,
    power: "190 ch",
    engine: "2.0 TwinPower Turbo",
    description: "BMW Série 3 berline, finition Sport Line. Véhicule puissant et confortable avec toutes les options BMW : navigation professionnelle, sièges chauffants, park assist. Historique complet BMW.",
    positivePoints: [
      "Finition Sport Line",
      "Navigation professionnelle",
      "Sièges chauffants",
      "Park Assist",
      "Historique complet BMW",
      "Distribution remplacée à 75 000 km",
    ],
    negativePoints: [
      "Petit accroc jante arrière gauche",
      "Frottement seuil de porte conducteur",
    ],
    images: [
      "/mock/vehicles/bmw-320d-1.jpg",
      "/mock/vehicles/bmw-320d-2.jpg",
      "/mock/vehicles/bmw-320d-3.jpg",
    ],
    featured: false,
    published: true,
    createdAt: "2026-07-20T10:00:00Z",
  },
  {
    id: "5",
    slug: "citroen-c3-feel-2022",
    brand: "Citroën",
    model: "C3 Feel",
    year: 2022,
    mileage: 18000,
    price: 13900,
    fuel: "Essence",
    transmission: "Manuelle",
    color: "Bleu Cobalt",
    doors: 5,
    seats: 5,
    power: "83 ch",
    engine: "1.2 PureTech",
    description: "Citroën C3 dernière génération, très faible kilométrage. Parfaite citadine confortable avec le programme Citroën Advanced Comfort. Idéale pour un premier véhicule ou usage urbain quotidien.",
    positivePoints: [
      "Très faible kilométrage",
      "Quasi neuve",
      "Apple CarPlay / Android Auto",
      "Sièges Advanced Comfort",
      "Sous garantie constructeur",
    ],
    negativePoints: [],
    images: [
      "/mock/vehicles/citroen-c3-1.jpg",
      "/mock/vehicles/citroen-c3-2.jpg",
      "/mock/vehicles/citroen-c3-3.jpg",
    ],
    featured: false,
    published: true,
    createdAt: "2026-08-10T10:00:00Z",
  },
  {
    id: "6",
    slug: "mercedes-classe-a-200-amg-line-2020",
    brand: "Mercedes",
    model: "Classe A 200 AMG Line",
    year: 2020,
    mileage: 62000,
    price: 29900,
    fuel: "Essence",
    transmission: "Automatique",
    color: "Noir Cosmos",
    doors: 5,
    seats: 5,
    power: "163 ch",
    engine: "1.3 Turbo",
    description: "Mercedes Classe A finition AMG Line, intérieur cuir/tissu dynamique. Système MBUX avec écran tactile, éclairage d'ambiance 64 couleurs, pack Premium. Un véhicule premium au quotidien.",
    positivePoints: [
      "Finition AMG Line complète",
      "MBUX dernière génération",
      "Pack Premium",
      "Éclairage ambiance 64 couleurs",
      "Caméra 360°",
      "Entretien Mercedes à jour",
    ],
    negativePoints: [
      "Micro-frottement rétroviseur droit",
    ],
    images: [
      "/mock/vehicles/mercedes-a200-1.jpg",
      "/mock/vehicles/mercedes-a200-2.jpg",
      "/mock/vehicles/mercedes-a200-3.jpg",
      "/mock/vehicles/mercedes-a200-4.jpg",
    ],
    featured: true,
    published: true,
    createdAt: "2026-08-03T10:00:00Z",
  },
  {
    id: "7",
    slug: "dacia-duster-prestige-2021",
    brand: "Dacia",
    model: "Duster Prestige",
    year: 2021,
    mileage: 41000,
    price: 17500,
    fuel: "Diesel",
    transmission: "Manuelle",
    color: "Brun Vison",
    doors: 5,
    seats: 5,
    power: "115 ch",
    engine: "1.5 Blue dCi",
    description: "Dacia Duster finition Prestige, la plus complète. SUV compact idéal pour la famille, avec caméra multiview, GPS, climatisation automatique. Rapport qualité/prix imbattable.",
    positivePoints: [
      "Finition Prestige complète",
      "Caméra multiview",
      "GPS MediaNav",
      "Climatisation automatique",
      "Barres de toit",
      "Attelage d'origine",
    ],
    negativePoints: [
      "Traces d'usage normales sur le hayon",
    ],
    images: [
      "/mock/vehicles/dacia-duster-1.jpg",
      "/mock/vehicles/dacia-duster-2.jpg",
      "/mock/vehicles/dacia-duster-3.jpg",
    ],
    featured: false,
    published: true,
    createdAt: "2026-07-28T10:00:00Z",
  },
  {
    id: "8",
    slug: "toyota-yaris-hybrid-2022",
    brand: "Toyota",
    model: "Yaris Hybrid",
    year: 2022,
    mileage: 25000,
    price: 19900,
    fuel: "Hybride",
    transmission: "Automatique",
    color: "Gris Manhattan",
    doors: 5,
    seats: 5,
    power: "116 ch",
    engine: "1.5 Hybrid Synergy Drive",
    description: "Toyota Yaris Hybrid dernière génération, consommation exceptionnelle. Moins de 4L/100km en usage mixte. Technologie hybride fiable et éprouvée Toyota. Véhicule idéal pour réduire sa consommation sans compromis.",
    positivePoints: [
      "Hybride — moins de 4L/100km",
      "Toyota Safety Sense complet",
      "Sous garantie constructeur",
      "Apple CarPlay sans fil",
      "Freinage régénératif",
      "Entretien Toyota à jour",
    ],
    negativePoints: [],
    images: [
      "/mock/vehicles/toyota-yaris-1.jpg",
      "/mock/vehicles/toyota-yaris-2.jpg",
      "/mock/vehicles/toyota-yaris-3.jpg",
    ],
    featured: false,
    published: true,
    createdAt: "2026-08-09T10:00:00Z",
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: "rdv-1",
    vehicleId: "1",
    vehicleLabel: "Peugeot 308 Style 2020",
    type: "agence",
    date: "2026-08-14",
    time: "14:00",
    name: "Jean Dupont",
    phone: "06 12 34 56 78",
    email: "jean.dupont@email.com",
    message: "Je souhaite voir la Peugeot 308 et faire un essai si possible.",
    status: "confirmé",
    createdAt: "2026-08-10T14:30:00Z",
  },
  {
    id: "rdv-2",
    vehicleId: "3",
    vehicleLabel: "Volkswagen Golf 8 Life 2021",
    type: "telephone",
    date: "2026-08-13",
    time: "10:30",
    name: "Marie Martin",
    phone: "07 98 76 54 32",
    email: "m.martin@email.com",
    message: "Questions sur le financement de la Golf.",
    status: "nouveau",
    createdAt: "2026-08-11T09:15:00Z",
  },
  {
    id: "rdv-3",
    vehicleId: "6",
    vehicleLabel: "Mercedes Classe A 200 AMG Line 2020",
    type: "agence",
    date: "2026-08-15",
    time: "16:00",
    name: "Karim Benzema",
    phone: "06 55 44 33 22",
    email: "k.benzema@email.com",
    status: "nouveau",
    createdAt: "2026-08-12T08:00:00Z",
  },
];

export const mockBuybackRequests: BuybackRequest[] = [
  {
    id: "rep-1",
    brand: "Ford",
    model: "Focus",
    year: 2017,
    mileage: 95000,
    condition: "État moyen",
    description: "Voiture familiale, quelques rayures sur les côtés, intérieur propre. Distribution faite à 90 000 km.",
    images: [],
    name: "Sophie Lemaire",
    phone: "06 11 22 33 44",
    email: "sophie.l@email.com",
    status: "nouveau",
    createdAt: "2026-08-11T16:00:00Z",
  },
  {
    id: "rep-2",
    brand: "Renault",
    model: "Megane 4",
    year: 2019,
    mileage: 67000,
    condition: "Bon état",
    description: "Mégane essence 1.3 TCe, finition Zen, GPS, radar de recul. Carnet d'entretien à jour.",
    images: [],
    name: "Ahmed Khedira",
    phone: "07 22 33 44 55",
    email: "ahmed.k@email.com",
    status: "en_estimation",
    createdAt: "2026-08-09T11:00:00Z",
  },
];

export const mockAlerts: VehicleAlert[] = [
  {
    id: "alrt-1",
    email: "lucas.petit@email.com",
    brand: "Peugeot",
    model: "3008",
    maxPrice: 25000,
    minYear: 2020,
    fuel: "Diesel",
    active: true,
    createdAt: "2026-08-05T12:00:00Z",
  },
  {
    id: "alrt-2",
    email: "emma.dubois@email.com",
    brand: "Toyota",
    maxPrice: 20000,
    minYear: 2021,
    fuel: "Hybride",
    active: true,
    createdAt: "2026-08-07T09:30:00Z",
  },
  {
    id: "alrt-3",
    email: "thomas.moreau@email.com",
    maxPrice: 15000,
    active: false,
    createdAt: "2026-07-20T14:00:00Z",
  },
];

export const mockAvailability: Availability[] = [
  { id: "av-1", dayOfWeek: 1, startTime: "10:00", endTime: "20:00", isOpen: true },
  { id: "av-2", dayOfWeek: 2, startTime: "10:00", endTime: "20:00", isOpen: true },
  { id: "av-3", dayOfWeek: 3, startTime: "10:00", endTime: "20:00", isOpen: true },
  { id: "av-4", dayOfWeek: 4, startTime: "10:00", endTime: "20:00", isOpen: true },
  { id: "av-5", dayOfWeek: 5, startTime: "10:00", endTime: "20:00", isOpen: true },
  { id: "av-6", dayOfWeek: 6, startTime: "10:00", endTime: "20:00", isOpen: true },
  { id: "av-7", dayOfWeek: 0, startTime: "10:00", endTime: "20:00", isOpen: true },
];

export const BRANDS = [
  "Peugeot", "Renault", "Citroën", "Volkswagen", "BMW", "Mercedes",
  "Audi", "Toyota", "Dacia", "Ford", "Opel", "Fiat", "Hyundai", "Kia",
  "Nissan", "Seat", "Skoda", "Volvo",
];

export const FUEL_TYPES = ["Essence", "Diesel", "Hybride", "Électrique"];
export const TRANSMISSION_TYPES = ["Manuelle", "Automatique"];
